name: Forecast Güncelleme

on:
  schedule:
    - cron: '0 4 * * *'  # 🕖 Her sabah saat 07:00'de (Türkiye saatiyle) çalışır
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      EVDS_API_KEY: ${{ secrets.EVDS_API_KEY }}
      GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}

    steps:
      - name: Kodu klonla
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gerekli kütüphaneleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Modeli eğit ve tahmin üret
        run: |
          python train_model.py

      - name: JSON dosyalarını GitHub'a push et
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add tahmin.json enflasyon_tahmin.json kur.json || true
          git commit -m "🌀 Otomatik güncelleme: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git pull --rebase
          git push
        continue-on-error: true